package com.zym.Design1.dao;

import com.zym.Design1.entity.CurrencyChange;
import com.zym.Design1.entity.CurrencyChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CurrencyChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    long countByExample(CurrencyChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByExample(CurrencyChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insert(CurrencyChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insertSelective(CurrencyChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    List<CurrencyChange> selectByExample(CurrencyChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    CurrencyChange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") CurrencyChange record, @Param("example") CurrencyChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExample(@Param("record") CurrencyChange record, @Param("example") CurrencyChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(CurrencyChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_change
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKey(CurrencyChange record);
}