package com.zym.Design1.dao;

import com.zym.Design1.entity.GoodsTrade;
import com.zym.Design1.entity.GoodsTradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    long countByExample(GoodsTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int deleteByExample(GoodsTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int insert(GoodsTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int insertSelective(GoodsTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    List<GoodsTrade> selectByExample(GoodsTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    GoodsTrade selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") GoodsTrade record, @Param("example") GoodsTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int updateByExample(@Param("record") GoodsTrade record, @Param("example") GoodsTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_trade
     *
     * @mbg.generated Wed May 16 16:55:04 CST 2018
     */
    int updateByPrimaryKey(GoodsTrade record);
}