package com.zym.Design1.dao;

import com.zym.Design1.entity.OrgRule;
import com.zym.Design1.entity.OrgRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    long countByExample(OrgRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByExample(OrgRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insert(OrgRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insertSelective(OrgRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    List<OrgRule> selectByExample(OrgRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    OrgRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrgRule record, @Param("example") OrgRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExample(@Param("record") OrgRule record, @Param("example") OrgRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(OrgRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_rule
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKey(OrgRule record);
}