package com.zym.Design1.dao;

import com.zym.Design1.entity.UserBonus;
import com.zym.Design1.entity.UserBonusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBonusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    long countByExample(UserBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByExample(UserBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insert(UserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int insertSelective(UserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    List<UserBonus> selectByExample(UserBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    UserBonus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserBonus record, @Param("example") UserBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByExample(@Param("record") UserBonus record, @Param("example") UserBonusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    int updateByPrimaryKey(UserBonus record);
}