package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BuyEcoinLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.serial_number1
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String serialNumber1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.serial_number2
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String serialNumber2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.amount
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_ecoin_log.after_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal afterEcoin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.id
     *
     * @return the value of buy_ecoin_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.id
     *
     * @param id the value for buy_ecoin_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.user_id
     *
     * @return the value of buy_ecoin_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.user_id
     *
     * @param userId the value for buy_ecoin_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.user_uid
     *
     * @return the value of buy_ecoin_log.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.user_uid
     *
     * @param userUid the value for buy_ecoin_log.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.date
     *
     * @return the value of buy_ecoin_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.date
     *
     * @param date the value for buy_ecoin_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.serial_number1
     *
     * @return the value of buy_ecoin_log.serial_number1
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getSerialNumber1() {
        return serialNumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.serial_number1
     *
     * @param serialNumber1 the value for buy_ecoin_log.serial_number1
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setSerialNumber1(String serialNumber1) {
        this.serialNumber1 = serialNumber1 == null ? null : serialNumber1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.serial_number2
     *
     * @return the value of buy_ecoin_log.serial_number2
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getSerialNumber2() {
        return serialNumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.serial_number2
     *
     * @param serialNumber2 the value for buy_ecoin_log.serial_number2
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setSerialNumber2(String serialNumber2) {
        this.serialNumber2 = serialNumber2 == null ? null : serialNumber2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.amount
     *
     * @return the value of buy_ecoin_log.amount
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.amount
     *
     * @param amount the value for buy_ecoin_log.amount
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.remark
     *
     * @return the value of buy_ecoin_log.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.remark
     *
     * @param remark the value for buy_ecoin_log.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_ecoin_log.after_ecoin
     *
     * @return the value of buy_ecoin_log.after_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getAfterEcoin() {
        return afterEcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_ecoin_log.after_ecoin
     *
     * @param afterEcoin the value for buy_ecoin_log.after_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAfterEcoin(BigDecimal afterEcoin) {
        this.afterEcoin = afterEcoin;
    }
}