package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CurrencyChange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_change.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_change.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_change.price
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_change.id
     *
     * @return the value of currency_change.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_change.id
     *
     * @param id the value for currency_change.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_change.date
     *
     * @return the value of currency_change.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_change.date
     *
     * @param date the value for currency_change.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_change.price
     *
     * @return the value of currency_change.price
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_change.price
     *
     * @param price the value for currency_change.price
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}