package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DailyReleaseLog {
    @Override
    public String toString() {
        return "DailyReleaseLog{" +
                "id=" + id +
                ", userId=" + userId +
                ", date=" + date +
                ", type='" + type + '\'' +
                ", entityId=" + entityId +
                ", entityUserLevel=" + entityUserLevel +
                ", ecoinBonus=" + ecoinBonus +
                ", unfrozenCoin=" + unfrozenCoin +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.entity_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer entityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.entity_user_level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer entityUserLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.ecoin_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal ecoinBonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.unfrozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal unfrozenCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.after_total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal afterTotalCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.after_tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal afterTradableCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column daily_release_log.after_release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal afterReleaseCoin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.id
     *
     * @return the value of daily_release_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.id
     *
     * @param id the value for daily_release_log.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.user_id
     *
     * @return the value of daily_release_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.user_id
     *
     * @param userId the value for daily_release_log.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.date
     *
     * @return the value of daily_release_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.date
     *
     * @param date the value for daily_release_log.date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.type
     *
     * @return the value of daily_release_log.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.type
     *
     * @param type the value for daily_release_log.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.entity_id
     *
     * @return the value of daily_release_log.entity_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.entity_id
     *
     * @param entityId the value for daily_release_log.entity_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.entity_user_level
     *
     * @return the value of daily_release_log.entity_user_level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getEntityUserLevel() {
        return entityUserLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.entity_user_level
     *
     * @param entityUserLevel the value for daily_release_log.entity_user_level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEntityUserLevel(Integer entityUserLevel) {
        this.entityUserLevel = entityUserLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.ecoin_bonus
     *
     * @return the value of daily_release_log.ecoin_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getEcoinBonus() {
        return ecoinBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.ecoin_bonus
     *
     * @param ecoinBonus the value for daily_release_log.ecoin_bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEcoinBonus(BigDecimal ecoinBonus) {
        this.ecoinBonus = ecoinBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.unfrozen_coin
     *
     * @return the value of daily_release_log.unfrozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getUnfrozenCoin() {
        return unfrozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.unfrozen_coin
     *
     * @param unfrozenCoin the value for daily_release_log.unfrozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUnfrozenCoin(BigDecimal unfrozenCoin) {
        this.unfrozenCoin = unfrozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.after_total_coin
     *
     * @return the value of daily_release_log.after_total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getAfterTotalCoin() {
        return afterTotalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.after_total_coin
     *
     * @param afterTotalCoin the value for daily_release_log.after_total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAfterTotalCoin(BigDecimal afterTotalCoin) {
        this.afterTotalCoin = afterTotalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.after_tradable_coin
     *
     * @return the value of daily_release_log.after_tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getAfterTradableCoin() {
        return afterTradableCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.after_tradable_coin
     *
     * @param afterTradableCoin the value for daily_release_log.after_tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAfterTradableCoin(BigDecimal afterTradableCoin) {
        this.afterTradableCoin = afterTradableCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column daily_release_log.after_release_coin
     *
     * @return the value of daily_release_log.after_release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getAfterReleaseCoin() {
        return afterReleaseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column daily_release_log.after_release_coin
     *
     * @param afterReleaseCoin the value for daily_release_log.after_release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAfterReleaseCoin(BigDecimal afterReleaseCoin) {
        this.afterReleaseCoin = afterReleaseCoin;
    }
}