package com.zym.Design1.entity;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private Integer goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.show_state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String showState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img
     *
     * @return the value of goods.img
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img
     *
     * @param img the value for goods.img
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.state
     *
     * @return the value of goods.state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.state
     *
     * @param state the value for goods.state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.show_state
     *
     * @return the value of goods.show_state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getShowState() {
        return showState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.show_state
     *
     * @param showState the value for goods.show_state
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setShowState(String showState) {
        this.showState = showState == null ? null : showState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated Tue May 22 23:57:49 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}