package com.zym.Design1.entity;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String userUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.created_date
     *
     * @return the value of notice.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.created_date
     *
     * @param createdDate the value for notice.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.modified_date
     *
     * @return the value of notice.modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.modified_date
     *
     * @param modifiedDate the value for notice.modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.state
     *
     * @return the value of notice.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.state
     *
     * @param state the value for notice.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_id
     *
     * @return the value of notice.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_id
     *
     * @param userId the value for notice.user_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.user_uid
     *
     * @return the value of notice.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.user_uid
     *
     * @param userUid the value for notice.user_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.version
     *
     * @return the value of notice.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.version
     *
     * @param version the value for notice.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}