package com.zym.Design1.entity;

import java.math.BigDecimal;

public class Rule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.rule_name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.id
     *
     * @return the value of rule.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.id
     *
     * @param id the value for rule.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.rule_name
     *
     * @return the value of rule.rule_name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.rule_name
     *
     * @param ruleName the value for rule.rule_name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.days
     *
     * @return the value of rule.days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.days
     *
     * @param days the value for rule.days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.bonus
     *
     * @return the value of rule.bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.bonus
     *
     * @param bonus the value for rule.bonus
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.type
     *
     * @return the value of rule.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.type
     *
     * @param type the value for rule.type
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule.remark
     *
     * @return the value of rule.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule.remark
     *
     * @param remark the value for rule.remark
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}