package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public TradeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(Date value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(Date value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(Date value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(Date value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(Date value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<Date> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<Date> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(Date value1, Date value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(Date value1, Date value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNull() {
            addCriterion("trade_date is null");
            return (Criteria) this;
        }

        public Criteria andTradeDateIsNotNull() {
            addCriterion("trade_date is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDateEqualTo(Date value) {
            addCriterion("trade_date =", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotEqualTo(Date value) {
            addCriterion("trade_date <>", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThan(Date value) {
            addCriterion("trade_date >", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("trade_date >=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThan(Date value) {
            addCriterion("trade_date <", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateLessThanOrEqualTo(Date value) {
            addCriterion("trade_date <=", value, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateIn(List<Date> values) {
            addCriterion("trade_date in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotIn(List<Date> values) {
            addCriterion("trade_date not in", values, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateBetween(Date value1, Date value2) {
            addCriterion("trade_date between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andTradeDateNotBetween(Date value1, Date value2) {
            addCriterion("trade_date not between", value1, value2, "tradeDate");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNull() {
            addCriterion("buyer_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNotNull() {
            addCriterion("buyer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdEqualTo(Integer value) {
            addCriterion("buyer_id =", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotEqualTo(Integer value) {
            addCriterion("buyer_id <>", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThan(Integer value) {
            addCriterion("buyer_id >", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_id >=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThan(Integer value) {
            addCriterion("buyer_id <", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_id <=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIn(List<Integer> values) {
            addCriterion("buyer_id in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotIn(List<Integer> values) {
            addCriterion("buyer_id not in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdBetween(Integer value1, Integer value2) {
            addCriterion("buyer_id between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_id not between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerUidIsNull() {
            addCriterion("buyer_uid is null");
            return (Criteria) this;
        }

        public Criteria andBuyerUidIsNotNull() {
            addCriterion("buyer_uid is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerUidEqualTo(String value) {
            addCriterion("buyer_uid =", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidNotEqualTo(String value) {
            addCriterion("buyer_uid <>", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidGreaterThan(String value) {
            addCriterion("buyer_uid >", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_uid >=", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidLessThan(String value) {
            addCriterion("buyer_uid <", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidLessThanOrEqualTo(String value) {
            addCriterion("buyer_uid <=", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidLike(String value) {
            addCriterion("buyer_uid like", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidNotLike(String value) {
            addCriterion("buyer_uid not like", value, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidIn(List<String> values) {
            addCriterion("buyer_uid in", values, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidNotIn(List<String> values) {
            addCriterion("buyer_uid not in", values, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidBetween(String value1, String value2) {
            addCriterion("buyer_uid between", value1, value2, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andBuyerUidNotBetween(String value1, String value2) {
            addCriterion("buyer_uid not between", value1, value2, "buyerUid");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Integer value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Integer value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Integer value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Integer value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Integer value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<Integer> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<Integer> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Integer value1, Integer value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerUidIsNull() {
            addCriterion("seller_uid is null");
            return (Criteria) this;
        }

        public Criteria andSellerUidIsNotNull() {
            addCriterion("seller_uid is not null");
            return (Criteria) this;
        }

        public Criteria andSellerUidEqualTo(String value) {
            addCriterion("seller_uid =", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotEqualTo(String value) {
            addCriterion("seller_uid <>", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidGreaterThan(String value) {
            addCriterion("seller_uid >", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidGreaterThanOrEqualTo(String value) {
            addCriterion("seller_uid >=", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLessThan(String value) {
            addCriterion("seller_uid <", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLessThanOrEqualTo(String value) {
            addCriterion("seller_uid <=", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLike(String value) {
            addCriterion("seller_uid like", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotLike(String value) {
            addCriterion("seller_uid not like", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidIn(List<String> values) {
            addCriterion("seller_uid in", values, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotIn(List<String> values) {
            addCriterion("seller_uid not in", values, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidBetween(String value1, String value2) {
            addCriterion("seller_uid between", value1, value2, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotBetween(String value1, String value2) {
            addCriterion("seller_uid not between", value1, value2, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andVcPriceIsNull() {
            addCriterion("vc_price is null");
            return (Criteria) this;
        }

        public Criteria andVcPriceIsNotNull() {
            addCriterion("vc_price is not null");
            return (Criteria) this;
        }

        public Criteria andVcPriceEqualTo(BigDecimal value) {
            addCriterion("vc_price =", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceNotEqualTo(BigDecimal value) {
            addCriterion("vc_price <>", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceGreaterThan(BigDecimal value) {
            addCriterion("vc_price >", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vc_price >=", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceLessThan(BigDecimal value) {
            addCriterion("vc_price <", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vc_price <=", value, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceIn(List<BigDecimal> values) {
            addCriterion("vc_price in", values, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceNotIn(List<BigDecimal> values) {
            addCriterion("vc_price not in", values, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vc_price between", value1, value2, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andVcPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vc_price not between", value1, value2, "vcPrice");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andEcoinIsNull() {
            addCriterion("ecoin is null");
            return (Criteria) this;
        }

        public Criteria andEcoinIsNotNull() {
            addCriterion("ecoin is not null");
            return (Criteria) this;
        }

        public Criteria andEcoinEqualTo(BigDecimal value) {
            addCriterion("ecoin =", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotEqualTo(BigDecimal value) {
            addCriterion("ecoin <>", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinGreaterThan(BigDecimal value) {
            addCriterion("ecoin >", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ecoin >=", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinLessThan(BigDecimal value) {
            addCriterion("ecoin <", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ecoin <=", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinIn(List<BigDecimal> values) {
            addCriterion("ecoin in", values, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotIn(List<BigDecimal> values) {
            addCriterion("ecoin not in", values, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ecoin between", value1, value2, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ecoin not between", value1, value2, "ecoin");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("last_modified_date is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("last_modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("last_modified_date =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("last_modified_date <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("last_modified_date >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modified_date >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("last_modified_date <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("last_modified_date <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("last_modified_date in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("last_modified_date not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerIsNull() {
            addCriterion("after_buyer is null");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerIsNotNull() {
            addCriterion("after_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerEqualTo(String value) {
            addCriterion("after_buyer =", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerNotEqualTo(String value) {
            addCriterion("after_buyer <>", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerGreaterThan(String value) {
            addCriterion("after_buyer >", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("after_buyer >=", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerLessThan(String value) {
            addCriterion("after_buyer <", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerLessThanOrEqualTo(String value) {
            addCriterion("after_buyer <=", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerLike(String value) {
            addCriterion("after_buyer like", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerNotLike(String value) {
            addCriterion("after_buyer not like", value, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerIn(List<String> values) {
            addCriterion("after_buyer in", values, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerNotIn(List<String> values) {
            addCriterion("after_buyer not in", values, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerBetween(String value1, String value2) {
            addCriterion("after_buyer between", value1, value2, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterBuyerNotBetween(String value1, String value2) {
            addCriterion("after_buyer not between", value1, value2, "afterBuyer");
            return (Criteria) this;
        }

        public Criteria andAfterSellerIsNull() {
            addCriterion("after_seller is null");
            return (Criteria) this;
        }

        public Criteria andAfterSellerIsNotNull() {
            addCriterion("after_seller is not null");
            return (Criteria) this;
        }

        public Criteria andAfterSellerEqualTo(String value) {
            addCriterion("after_seller =", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerNotEqualTo(String value) {
            addCriterion("after_seller <>", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerGreaterThan(String value) {
            addCriterion("after_seller >", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerGreaterThanOrEqualTo(String value) {
            addCriterion("after_seller >=", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerLessThan(String value) {
            addCriterion("after_seller <", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerLessThanOrEqualTo(String value) {
            addCriterion("after_seller <=", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerLike(String value) {
            addCriterion("after_seller like", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerNotLike(String value) {
            addCriterion("after_seller not like", value, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerIn(List<String> values) {
            addCriterion("after_seller in", values, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerNotIn(List<String> values) {
            addCriterion("after_seller not in", values, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerBetween(String value1, String value2) {
            addCriterion("after_seller between", value1, value2, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andAfterSellerNotBetween(String value1, String value2) {
            addCriterion("after_seller not between", value1, value2, "afterSeller");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSrcIdIsNull() {
            addCriterion("src_id is null");
            return (Criteria) this;
        }

        public Criteria andSrcIdIsNotNull() {
            addCriterion("src_id is not null");
            return (Criteria) this;
        }

        public Criteria andSrcIdEqualTo(Long value) {
            addCriterion("src_id =", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdNotEqualTo(Long value) {
            addCriterion("src_id <>", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdGreaterThan(Long value) {
            addCriterion("src_id >", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdGreaterThanOrEqualTo(Long value) {
            addCriterion("src_id >=", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdLessThan(Long value) {
            addCriterion("src_id <", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdLessThanOrEqualTo(Long value) {
            addCriterion("src_id <=", value, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdIn(List<Long> values) {
            addCriterion("src_id in", values, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdNotIn(List<Long> values) {
            addCriterion("src_id not in", values, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdBetween(Long value1, Long value2) {
            addCriterion("src_id between", value1, value2, "srcId");
            return (Criteria) this;
        }

        public Criteria andSrcIdNotBetween(Long value1, Long value2) {
            addCriterion("src_id not between", value1, value2, "srcId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("rule_id is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("rule_id is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(Integer value) {
            addCriterion("rule_id =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(Integer value) {
            addCriterion("rule_id <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(Integer value) {
            addCriterion("rule_id >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_id >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(Integer value) {
            addCriterion("rule_id <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("rule_id <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<Integer> values) {
            addCriterion("rule_id in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<Integer> values) {
            addCriterion("rule_id not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(Integer value1, Integer value2) {
            addCriterion("rule_id between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_id not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade
     *
     * @mbg.generated do_not_delete_during_merge Tue May 01 23:51:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}