package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("img is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("img is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("img =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("img <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("img >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("img >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("img <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("img <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("img like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("img not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("img in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("img not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("img between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("img not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("role like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("role not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("id_number is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("id_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("id_number =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("id_number <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("id_number >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("id_number >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("id_number <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("id_number <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("id_number like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("id_number not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("id_number in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("id_number not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("id_number between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("id_number not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andDepositBankIsNull() {
            addCriterion("deposit_bank is null");
            return (Criteria) this;
        }

        public Criteria andDepositBankIsNotNull() {
            addCriterion("deposit_bank is not null");
            return (Criteria) this;
        }

        public Criteria andDepositBankEqualTo(String value) {
            addCriterion("deposit_bank =", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankNotEqualTo(String value) {
            addCriterion("deposit_bank <>", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankGreaterThan(String value) {
            addCriterion("deposit_bank >", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankGreaterThanOrEqualTo(String value) {
            addCriterion("deposit_bank >=", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankLessThan(String value) {
            addCriterion("deposit_bank <", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankLessThanOrEqualTo(String value) {
            addCriterion("deposit_bank <=", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankLike(String value) {
            addCriterion("deposit_bank like", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankNotLike(String value) {
            addCriterion("deposit_bank not like", value, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankIn(List<String> values) {
            addCriterion("deposit_bank in", values, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankNotIn(List<String> values) {
            addCriterion("deposit_bank not in", values, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankBetween(String value1, String value2) {
            addCriterion("deposit_bank between", value1, value2, "depositBank");
            return (Criteria) this;
        }

        public Criteria andDepositBankNotBetween(String value1, String value2) {
            addCriterion("deposit_bank not between", value1, value2, "depositBank");
            return (Criteria) this;
        }

        public Criteria andAccountHolderIsNull() {
            addCriterion("account_holder is null");
            return (Criteria) this;
        }

        public Criteria andAccountHolderIsNotNull() {
            addCriterion("account_holder is not null");
            return (Criteria) this;
        }

        public Criteria andAccountHolderEqualTo(String value) {
            addCriterion("account_holder =", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderNotEqualTo(String value) {
            addCriterion("account_holder <>", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderGreaterThan(String value) {
            addCriterion("account_holder >", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderGreaterThanOrEqualTo(String value) {
            addCriterion("account_holder >=", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderLessThan(String value) {
            addCriterion("account_holder <", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderLessThanOrEqualTo(String value) {
            addCriterion("account_holder <=", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderLike(String value) {
            addCriterion("account_holder like", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderNotLike(String value) {
            addCriterion("account_holder not like", value, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderIn(List<String> values) {
            addCriterion("account_holder in", values, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderNotIn(List<String> values) {
            addCriterion("account_holder not in", values, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderBetween(String value1, String value2) {
            addCriterion("account_holder between", value1, value2, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andAccountHolderNotBetween(String value1, String value2) {
            addCriterion("account_holder not between", value1, value2, "accountHolder");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNull() {
            addCriterion("bank_account is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNotNull() {
            addCriterion("bank_account is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountEqualTo(String value) {
            addCriterion("bank_account =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotEqualTo(String value) {
            addCriterion("bank_account <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThan(String value) {
            addCriterion("bank_account >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bank_account >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThan(String value) {
            addCriterion("bank_account <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThanOrEqualTo(String value) {
            addCriterion("bank_account <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLike(String value) {
            addCriterion("bank_account like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotLike(String value) {
            addCriterion("bank_account not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIn(List<String> values) {
            addCriterion("bank_account in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotIn(List<String> values) {
            addCriterion("bank_account not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountBetween(String value1, String value2) {
            addCriterion("bank_account between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotBetween(String value1, String value2) {
            addCriterion("bank_account not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysIsNull() {
            addCriterion("release_days is null");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysIsNotNull() {
            addCriterion("release_days is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysEqualTo(Integer value) {
            addCriterion("release_days =", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysNotEqualTo(Integer value) {
            addCriterion("release_days <>", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysGreaterThan(Integer value) {
            addCriterion("release_days >", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("release_days >=", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysLessThan(Integer value) {
            addCriterion("release_days <", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysLessThanOrEqualTo(Integer value) {
            addCriterion("release_days <=", value, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysIn(List<Integer> values) {
            addCriterion("release_days in", values, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysNotIn(List<Integer> values) {
            addCriterion("release_days not in", values, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysBetween(Integer value1, Integer value2) {
            addCriterion("release_days between", value1, value2, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andReleaseDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("release_days not between", value1, value2, "releaseDays");
            return (Criteria) this;
        }

        public Criteria andEcoinIsNull() {
            addCriterion("ecoin is null");
            return (Criteria) this;
        }

        public Criteria andEcoinIsNotNull() {
            addCriterion("ecoin is not null");
            return (Criteria) this;
        }

        public Criteria andEcoinEqualTo(BigDecimal value) {
            addCriterion("ecoin =", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotEqualTo(BigDecimal value) {
            addCriterion("ecoin <>", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinGreaterThan(BigDecimal value) {
            addCriterion("ecoin >", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ecoin >=", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinLessThan(BigDecimal value) {
            addCriterion("ecoin <", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ecoin <=", value, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinIn(List<BigDecimal> values) {
            addCriterion("ecoin in", values, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotIn(List<BigDecimal> values) {
            addCriterion("ecoin not in", values, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ecoin between", value1, value2, "ecoin");
            return (Criteria) this;
        }

        public Criteria andEcoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ecoin not between", value1, value2, "ecoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinIsNull() {
            addCriterion("total_coin is null");
            return (Criteria) this;
        }

        public Criteria andTotalCoinIsNotNull() {
            addCriterion("total_coin is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCoinEqualTo(BigDecimal value) {
            addCriterion("total_coin =", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinNotEqualTo(BigDecimal value) {
            addCriterion("total_coin <>", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinGreaterThan(BigDecimal value) {
            addCriterion("total_coin >", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_coin >=", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinLessThan(BigDecimal value) {
            addCriterion("total_coin <", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_coin <=", value, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinIn(List<BigDecimal> values) {
            addCriterion("total_coin in", values, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinNotIn(List<BigDecimal> values) {
            addCriterion("total_coin not in", values, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_coin between", value1, value2, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andTotalCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_coin not between", value1, value2, "totalCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinIsNull() {
            addCriterion("on_sale_coin is null");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinIsNotNull() {
            addCriterion("on_sale_coin is not null");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinEqualTo(BigDecimal value) {
            addCriterion("on_sale_coin =", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinNotEqualTo(BigDecimal value) {
            addCriterion("on_sale_coin <>", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinGreaterThan(BigDecimal value) {
            addCriterion("on_sale_coin >", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("on_sale_coin >=", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinLessThan(BigDecimal value) {
            addCriterion("on_sale_coin <", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("on_sale_coin <=", value, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinIn(List<BigDecimal> values) {
            addCriterion("on_sale_coin in", values, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinNotIn(List<BigDecimal> values) {
            addCriterion("on_sale_coin not in", values, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_sale_coin between", value1, value2, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andOnSaleCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_sale_coin not between", value1, value2, "onSaleCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinIsNull() {
            addCriterion("tradable_coin is null");
            return (Criteria) this;
        }

        public Criteria andTradableCoinIsNotNull() {
            addCriterion("tradable_coin is not null");
            return (Criteria) this;
        }

        public Criteria andTradableCoinEqualTo(BigDecimal value) {
            addCriterion("tradable_coin =", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinNotEqualTo(BigDecimal value) {
            addCriterion("tradable_coin <>", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinGreaterThan(BigDecimal value) {
            addCriterion("tradable_coin >", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tradable_coin >=", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinLessThan(BigDecimal value) {
            addCriterion("tradable_coin <", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tradable_coin <=", value, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinIn(List<BigDecimal> values) {
            addCriterion("tradable_coin in", values, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinNotIn(List<BigDecimal> values) {
            addCriterion("tradable_coin not in", values, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tradable_coin between", value1, value2, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andTradableCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tradable_coin not between", value1, value2, "tradableCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinIsNull() {
            addCriterion("sold_coin is null");
            return (Criteria) this;
        }

        public Criteria andSoldCoinIsNotNull() {
            addCriterion("sold_coin is not null");
            return (Criteria) this;
        }

        public Criteria andSoldCoinEqualTo(BigDecimal value) {
            addCriterion("sold_coin =", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinNotEqualTo(BigDecimal value) {
            addCriterion("sold_coin <>", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinGreaterThan(BigDecimal value) {
            addCriterion("sold_coin >", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sold_coin >=", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinLessThan(BigDecimal value) {
            addCriterion("sold_coin <", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sold_coin <=", value, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinIn(List<BigDecimal> values) {
            addCriterion("sold_coin in", values, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinNotIn(List<BigDecimal> values) {
            addCriterion("sold_coin not in", values, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sold_coin between", value1, value2, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andSoldCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sold_coin not between", value1, value2, "soldCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinIsNull() {
            addCriterion("release_coin is null");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinIsNotNull() {
            addCriterion("release_coin is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinEqualTo(BigDecimal value) {
            addCriterion("release_coin =", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinNotEqualTo(BigDecimal value) {
            addCriterion("release_coin <>", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinGreaterThan(BigDecimal value) {
            addCriterion("release_coin >", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("release_coin >=", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinLessThan(BigDecimal value) {
            addCriterion("release_coin <", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("release_coin <=", value, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinIn(List<BigDecimal> values) {
            addCriterion("release_coin in", values, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinNotIn(List<BigDecimal> values) {
            addCriterion("release_coin not in", values, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("release_coin between", value1, value2, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("release_coin not between", value1, value2, "releaseCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinIsNull() {
            addCriterion("release_frozen_coin is null");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinIsNotNull() {
            addCriterion("release_frozen_coin is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinEqualTo(BigDecimal value) {
            addCriterion("release_frozen_coin =", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinNotEqualTo(BigDecimal value) {
            addCriterion("release_frozen_coin <>", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinGreaterThan(BigDecimal value) {
            addCriterion("release_frozen_coin >", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("release_frozen_coin >=", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinLessThan(BigDecimal value) {
            addCriterion("release_frozen_coin <", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("release_frozen_coin <=", value, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinIn(List<BigDecimal> values) {
            addCriterion("release_frozen_coin in", values, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinNotIn(List<BigDecimal> values) {
            addCriterion("release_frozen_coin not in", values, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("release_frozen_coin between", value1, value2, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andReleaseFrozenCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("release_frozen_coin not between", value1, value2, "releaseFrozenCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinIsNull() {
            addCriterion("encash_frozen_cash_coin is null");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinIsNotNull() {
            addCriterion("encash_frozen_cash_coin is not null");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinEqualTo(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin =", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinNotEqualTo(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin <>", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinGreaterThan(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin >", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin >=", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinLessThan(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin <", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("encash_frozen_cash_coin <=", value, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinIn(List<BigDecimal> values) {
            addCriterion("encash_frozen_cash_coin in", values, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinNotIn(List<BigDecimal> values) {
            addCriterion("encash_frozen_cash_coin not in", values, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("encash_frozen_cash_coin between", value1, value2, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andEncashFrozenCashCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("encash_frozen_cash_coin not between", value1, value2, "encashFrozenCashCoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinIsNull() {
            addCriterion("on_buy_ecoin is null");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinIsNotNull() {
            addCriterion("on_buy_ecoin is not null");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinEqualTo(BigDecimal value) {
            addCriterion("on_buy_ecoin =", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinNotEqualTo(BigDecimal value) {
            addCriterion("on_buy_ecoin <>", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinGreaterThan(BigDecimal value) {
            addCriterion("on_buy_ecoin >", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("on_buy_ecoin >=", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinLessThan(BigDecimal value) {
            addCriterion("on_buy_ecoin <", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("on_buy_ecoin <=", value, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinIn(List<BigDecimal> values) {
            addCriterion("on_buy_ecoin in", values, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinNotIn(List<BigDecimal> values) {
            addCriterion("on_buy_ecoin not in", values, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_buy_ecoin between", value1, value2, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andOnBuyEcoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_buy_ecoin not between", value1, value2, "onBuyEcoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinIsNull() {
            addCriterion("cash_coin is null");
            return (Criteria) this;
        }

        public Criteria andCashCoinIsNotNull() {
            addCriterion("cash_coin is not null");
            return (Criteria) this;
        }

        public Criteria andCashCoinEqualTo(BigDecimal value) {
            addCriterion("cash_coin =", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinNotEqualTo(BigDecimal value) {
            addCriterion("cash_coin <>", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinGreaterThan(BigDecimal value) {
            addCriterion("cash_coin >", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_coin >=", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinLessThan(BigDecimal value) {
            addCriterion("cash_coin <", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_coin <=", value, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinIn(List<BigDecimal> values) {
            addCriterion("cash_coin in", values, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinNotIn(List<BigDecimal> values) {
            addCriterion("cash_coin not in", values, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_coin between", value1, value2, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andCashCoinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_coin not between", value1, value2, "cashCoin");
            return (Criteria) this;
        }

        public Criteria andEarningsIsNull() {
            addCriterion("earnings is null");
            return (Criteria) this;
        }

        public Criteria andEarningsIsNotNull() {
            addCriterion("earnings is not null");
            return (Criteria) this;
        }

        public Criteria andEarningsEqualTo(BigDecimal value) {
            addCriterion("earnings =", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsNotEqualTo(BigDecimal value) {
            addCriterion("earnings <>", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsGreaterThan(BigDecimal value) {
            addCriterion("earnings >", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings >=", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsLessThan(BigDecimal value) {
            addCriterion("earnings <", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings <=", value, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsIn(List<BigDecimal> values) {
            addCriterion("earnings in", values, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsNotIn(List<BigDecimal> values) {
            addCriterion("earnings not in", values, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings between", value1, value2, "earnings");
            return (Criteria) this;
        }

        public Criteria andEarningsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings not between", value1, value2, "earnings");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdIsNull() {
            addCriterion("introducer_id is null");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdIsNotNull() {
            addCriterion("introducer_id is not null");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdEqualTo(Integer value) {
            addCriterion("introducer_id =", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdNotEqualTo(Integer value) {
            addCriterion("introducer_id <>", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdGreaterThan(Integer value) {
            addCriterion("introducer_id >", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("introducer_id >=", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdLessThan(Integer value) {
            addCriterion("introducer_id <", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdLessThanOrEqualTo(Integer value) {
            addCriterion("introducer_id <=", value, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdIn(List<Integer> values) {
            addCriterion("introducer_id in", values, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdNotIn(List<Integer> values) {
            addCriterion("introducer_id not in", values, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdBetween(Integer value1, Integer value2) {
            addCriterion("introducer_id between", value1, value2, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("introducer_id not between", value1, value2, "introducerId");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidIsNull() {
            addCriterion("introducer_uid is null");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidIsNotNull() {
            addCriterion("introducer_uid is not null");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidEqualTo(String value) {
            addCriterion("introducer_uid =", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidNotEqualTo(String value) {
            addCriterion("introducer_uid <>", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidGreaterThan(String value) {
            addCriterion("introducer_uid >", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidGreaterThanOrEqualTo(String value) {
            addCriterion("introducer_uid >=", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidLessThan(String value) {
            addCriterion("introducer_uid <", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidLessThanOrEqualTo(String value) {
            addCriterion("introducer_uid <=", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidLike(String value) {
            addCriterion("introducer_uid like", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidNotLike(String value) {
            addCriterion("introducer_uid not like", value, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidIn(List<String> values) {
            addCriterion("introducer_uid in", values, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidNotIn(List<String> values) {
            addCriterion("introducer_uid not in", values, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidBetween(String value1, String value2) {
            addCriterion("introducer_uid between", value1, value2, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andIntroducerUidNotBetween(String value1, String value2) {
            addCriterion("introducer_uid not between", value1, value2, "introducerUid");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagIsNull() {
            addCriterion("ecoin_set_flag is null");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagIsNotNull() {
            addCriterion("ecoin_set_flag is not null");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagEqualTo(String value) {
            addCriterion("ecoin_set_flag =", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagNotEqualTo(String value) {
            addCriterion("ecoin_set_flag <>", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagGreaterThan(String value) {
            addCriterion("ecoin_set_flag >", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ecoin_set_flag >=", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagLessThan(String value) {
            addCriterion("ecoin_set_flag <", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagLessThanOrEqualTo(String value) {
            addCriterion("ecoin_set_flag <=", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagLike(String value) {
            addCriterion("ecoin_set_flag like", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagNotLike(String value) {
            addCriterion("ecoin_set_flag not like", value, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagIn(List<String> values) {
            addCriterion("ecoin_set_flag in", values, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagNotIn(List<String> values) {
            addCriterion("ecoin_set_flag not in", values, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagBetween(String value1, String value2) {
            addCriterion("ecoin_set_flag between", value1, value2, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andEcoinSetFlagNotBetween(String value1, String value2) {
            addCriterion("ecoin_set_flag not between", value1, value2, "ecoinSetFlag");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNull() {
            addCriterion("rule_id is null");
            return (Criteria) this;
        }

        public Criteria andRuleIdIsNotNull() {
            addCriterion("rule_id is not null");
            return (Criteria) this;
        }

        public Criteria andRuleIdEqualTo(Integer value) {
            addCriterion("rule_id =", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotEqualTo(Integer value) {
            addCriterion("rule_id <>", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThan(Integer value) {
            addCriterion("rule_id >", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_id >=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThan(Integer value) {
            addCriterion("rule_id <", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("rule_id <=", value, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdIn(List<Integer> values) {
            addCriterion("rule_id in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotIn(List<Integer> values) {
            addCriterion("rule_id not in", values, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdBetween(Integer value1, Integer value2) {
            addCriterion("rule_id between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andRuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_id not between", value1, value2, "ruleId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNull() {
            addCriterion("trade_password is null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNotNull() {
            addCriterion("trade_password is not null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordEqualTo(String value) {
            addCriterion("trade_password =", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotEqualTo(String value) {
            addCriterion("trade_password <>", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThan(String value) {
            addCriterion("trade_password >", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("trade_password >=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThan(String value) {
            addCriterion("trade_password <", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThanOrEqualTo(String value) {
            addCriterion("trade_password <=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLike(String value) {
            addCriterion("trade_password like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotLike(String value) {
            addCriterion("trade_password not like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIn(List<String> values) {
            addCriterion("trade_password in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotIn(List<String> values) {
            addCriterion("trade_password not in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordBetween(String value1, String value2) {
            addCriterion("trade_password between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotBetween(String value1, String value2) {
            addCriterion("trade_password not between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradeSaltIsNull() {
            addCriterion("trade_salt is null");
            return (Criteria) this;
        }

        public Criteria andTradeSaltIsNotNull() {
            addCriterion("trade_salt is not null");
            return (Criteria) this;
        }

        public Criteria andTradeSaltEqualTo(String value) {
            addCriterion("trade_salt =", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltNotEqualTo(String value) {
            addCriterion("trade_salt <>", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltGreaterThan(String value) {
            addCriterion("trade_salt >", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltGreaterThanOrEqualTo(String value) {
            addCriterion("trade_salt >=", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltLessThan(String value) {
            addCriterion("trade_salt <", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltLessThanOrEqualTo(String value) {
            addCriterion("trade_salt <=", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltLike(String value) {
            addCriterion("trade_salt like", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltNotLike(String value) {
            addCriterion("trade_salt not like", value, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltIn(List<String> values) {
            addCriterion("trade_salt in", values, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltNotIn(List<String> values) {
            addCriterion("trade_salt not in", values, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltBetween(String value1, String value2) {
            addCriterion("trade_salt between", value1, value2, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andTradeSaltNotBetween(String value1, String value2) {
            addCriterion("trade_salt not between", value1, value2, "tradeSalt");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("last_modified_date is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("last_modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("last_modified_date =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("last_modified_date <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("last_modified_date >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modified_date >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("last_modified_date <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("last_modified_date <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("last_modified_date in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("last_modified_date not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andShopPointsIsNull() {
            addCriterion("shop_points is null");
            return (Criteria) this;
        }

        public Criteria andShopPointsIsNotNull() {
            addCriterion("shop_points is not null");
            return (Criteria) this;
        }

        public Criteria andShopPointsEqualTo(BigDecimal value) {
            addCriterion("shop_points =", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsNotEqualTo(BigDecimal value) {
            addCriterion("shop_points <>", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsGreaterThan(BigDecimal value) {
            addCriterion("shop_points >", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("shop_points >=", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsLessThan(BigDecimal value) {
            addCriterion("shop_points <", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("shop_points <=", value, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsIn(List<BigDecimal> values) {
            addCriterion("shop_points in", values, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsNotIn(List<BigDecimal> values) {
            addCriterion("shop_points not in", values, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shop_points between", value1, value2, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andShopPointsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("shop_points not between", value1, value2, "shopPoints");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Tue May 01 23:51:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}