package com.zym.Design1.entity;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", uid='" + uid + '\'' +
                ", rlsD=" + releaseDays +
                ", ecoin=" + ecoin +
                ", totC=" + totalCoin +
                ", onSC=" + onSaleCoin +
                ", trdbC=" + tradableCoin +
                ", soldC=" + soldCoin +
                ", rlsC=" + releaseCoin +
                ", rlsFrzC=" + releaseFrozenCoin +
                ", encashFrzCashC=" + encashFrozenCashCoin +
                ", onBuyEc=" + onBuyEcoin +
                ", cashC=" + cashCoin +
                ", earnings=" + earnings +
                ", shopP=" + shopPoints +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id_number
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deposit_bank
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String depositBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_holder
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String accountHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.bank_account
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.release_days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer releaseDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal ecoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal totalCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.on_sale_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal onSaleCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal tradableCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sold_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal soldCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal releaseCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.release_frozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal releaseFrozenCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.encash_frozen_cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal encashFrozenCashCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.on_buy_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal onBuyEcoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal cashCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.earnings
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal earnings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.introducer_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer introducerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.introducer_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String introducerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ecoin_set_flag
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String ecoinSetFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rule_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.trade_password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String tradePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.trade_salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private String tradeSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Date lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shop_points
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private BigDecimal shopPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salt
     *
     * @return the value of user.salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salt
     *
     * @param salt the value for user.salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_date
     *
     * @return the value of user.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_date
     *
     * @param createdDate the value for user.created_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img
     *
     * @return the value of user.img
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img
     *
     * @param img the value for user.img
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id_number
     *
     * @return the value of user.id_number
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id_number
     *
     * @param idNumber the value for user.id_number
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deposit_bank
     *
     * @return the value of user.deposit_bank
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deposit_bank
     *
     * @param depositBank the value for user.deposit_bank
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank == null ? null : depositBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account_holder
     *
     * @return the value of user.account_holder
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getAccountHolder() {
        return accountHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account_holder
     *
     * @param accountHolder the value for user.account_holder
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAccountHolder(String accountHolder) {
        this.accountHolder = accountHolder == null ? null : accountHolder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.bank_account
     *
     * @return the value of user.bank_account
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.bank_account
     *
     * @param bankAccount the value for user.bank_account
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.release_days
     *
     * @return the value of user.release_days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getReleaseDays() {
        return releaseDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.release_days
     *
     * @param releaseDays the value for user.release_days
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setReleaseDays(Integer releaseDays) {
        this.releaseDays = releaseDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ecoin
     *
     * @return the value of user.ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getEcoin() {
        return ecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ecoin
     *
     * @param ecoin the value for user.ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEcoin(BigDecimal ecoin) {
        this.ecoin = ecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.total_coin
     *
     * @return the value of user.total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getTotalCoin() {
        return totalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.total_coin
     *
     * @param totalCoin the value for user.total_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setTotalCoin(BigDecimal totalCoin) {
        this.totalCoin = totalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.on_sale_coin
     *
     * @return the value of user.on_sale_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getOnSaleCoin() {
        return onSaleCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.on_sale_coin
     *
     * @param onSaleCoin the value for user.on_sale_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setOnSaleCoin(BigDecimal onSaleCoin) {
        this.onSaleCoin = onSaleCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tradable_coin
     *
     * @return the value of user.tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getTradableCoin() {
        return tradableCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tradable_coin
     *
     * @param tradableCoin the value for user.tradable_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setTradableCoin(BigDecimal tradableCoin) {
        this.tradableCoin = tradableCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sold_coin
     *
     * @return the value of user.sold_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getSoldCoin() {
        return soldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sold_coin
     *
     * @param soldCoin the value for user.sold_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setSoldCoin(BigDecimal soldCoin) {
        this.soldCoin = soldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.release_coin
     *
     * @return the value of user.release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getReleaseCoin() {
        return releaseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.release_coin
     *
     * @param releaseCoin the value for user.release_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setReleaseCoin(BigDecimal releaseCoin) {
        this.releaseCoin = releaseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.release_frozen_coin
     *
     * @return the value of user.release_frozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getReleaseFrozenCoin() {
        return releaseFrozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.release_frozen_coin
     *
     * @param releaseFrozenCoin the value for user.release_frozen_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setReleaseFrozenCoin(BigDecimal releaseFrozenCoin) {
        this.releaseFrozenCoin = releaseFrozenCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.encash_frozen_cash_coin
     *
     * @return the value of user.encash_frozen_cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getEncashFrozenCashCoin() {
        return encashFrozenCashCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.encash_frozen_cash_coin
     *
     * @param encashFrozenCashCoin the value for user.encash_frozen_cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEncashFrozenCashCoin(BigDecimal encashFrozenCashCoin) {
        this.encashFrozenCashCoin = encashFrozenCashCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.on_buy_ecoin
     *
     * @return the value of user.on_buy_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getOnBuyEcoin() {
        return onBuyEcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.on_buy_ecoin
     *
     * @param onBuyEcoin the value for user.on_buy_ecoin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setOnBuyEcoin(BigDecimal onBuyEcoin) {
        this.onBuyEcoin = onBuyEcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cash_coin
     *
     * @return the value of user.cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getCashCoin() {
        return cashCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cash_coin
     *
     * @param cashCoin the value for user.cash_coin
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setCashCoin(BigDecimal cashCoin) {
        this.cashCoin = cashCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.earnings
     *
     * @return the value of user.earnings
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getEarnings() {
        return earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.earnings
     *
     * @param earnings the value for user.earnings
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEarnings(BigDecimal earnings) {
        this.earnings = earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.introducer_id
     *
     * @return the value of user.introducer_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getIntroducerId() {
        return introducerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.introducer_id
     *
     * @param introducerId the value for user.introducer_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setIntroducerId(Integer introducerId) {
        this.introducerId = introducerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.introducer_uid
     *
     * @return the value of user.introducer_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getIntroducerUid() {
        return introducerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.introducer_uid
     *
     * @param introducerUid the value for user.introducer_uid
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setIntroducerUid(String introducerUid) {
        this.introducerUid = introducerUid == null ? null : introducerUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ecoin_set_flag
     *
     * @return the value of user.ecoin_set_flag
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getEcoinSetFlag() {
        return ecoinSetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ecoin_set_flag
     *
     * @param ecoinSetFlag the value for user.ecoin_set_flag
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setEcoinSetFlag(String ecoinSetFlag) {
        this.ecoinSetFlag = ecoinSetFlag == null ? null : ecoinSetFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rule_id
     *
     * @return the value of user.rule_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rule_id
     *
     * @param ruleId the value for user.rule_id
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.trade_password
     *
     * @return the value of user.trade_password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getTradePassword() {
        return tradePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.trade_password
     *
     * @param tradePassword the value for user.trade_password
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setTradePassword(String tradePassword) {
        this.tradePassword = tradePassword == null ? null : tradePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.trade_salt
     *
     * @return the value of user.trade_salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public String getTradeSalt() {
        return tradeSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.trade_salt
     *
     * @param tradeSalt the value for user.trade_salt
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setTradeSalt(String tradeSalt) {
        this.tradeSalt = tradeSalt == null ? null : tradeSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_modified_date
     *
     * @return the value of user.last_modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_modified_date
     *
     * @param lastModifiedDate the value for user.last_modified_date
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shop_points
     *
     * @return the value of user.shop_points
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public BigDecimal getShopPoints() {
        return shopPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shop_points
     *
     * @param shopPoints the value for user.shop_points
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setShopPoints(BigDecimal shopPoints) {
        this.shopPoints = shopPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.version
     *
     * @return the value of user.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.version
     *
     * @param version the value for user.version
     *
     * @mbg.generated Tue May 01 23:51:54 CST 2018
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}